--
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XMODIFIERS", "@im=fcitx")

-- XDG Specifications
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

-- Toolkit Backend
hl.env("CLUTTER_BACKEND", "wayland")

-- Qt
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_WAYLAND_RECONNECT", "1")

-- Cursor
hl.env("XCURSOR_THEME", "Paper")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Paper")
hl.env("HYPRCURSOR_SIZE", "24")
