-- Generated by nwg-displays on 2026-04-13 at 16:12:26. Do not edit manually.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x40A9",
    mode = "1920x1080@60.01",
    position = "0x0",
    scale = "1.5",
})

