[tools]
bun = "latest"
chezmoi = "latest"
claude = "latest"
duckdb = "latest"
github-cli = "latest"
"github:daeuniverse/daed" = "latest"
"github:e-tho/bzmenu" = "latest"
"github:e-tho/iwmenu" = "latest"
"github:jing2uo/kontext" = "latest"
"github:jing2uo/tdx2db" = "latest"
"github:sinelaw/fresh" = "latest"
go = "latest"
"http:longbridge" = { version = "latest", url = "https://assets.lbkrs.com/github/release/longbridge-desktop/stable/longbridge-v{{version}}-linux-x86_64.AppImage", bin = "longbridge", version_list_url = "https://assets.lbkrs.com/github/release/longbridge-desktop/stable/latest.json", version_json_path = ".version" }
node = "latest"
opencode = "latest"
usage = "latest"
uv = "latest"
yt-dlp = "latest"
