[tools]
"aqua:loft-sh/devpod" = "latest"
bun = "latest"
chezmoi = "latest"
claude = "latest"
codex = "latest"
duckdb = "latest"
github-cli = "latest"
"github:daeuniverse/daed" = { version = "latest", version_prefix = "v" }
"github:e-tho/bzmenu" = "latest"
"github:e-tho/iwmenu" = "latest"
"github:jing2uo/kontext" = "latest"
go = "latest"
node = "latest"
opencode = "latest"
pulumi = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
wrangler = "latest"
yt-dlp = "latest"
zellij = "latest"

[settings]
minimum_release_age = "0"
